PATCH http://localhost:3300/posts/
Content-Type: application/json
{
    "id": 17,
    "title": "Arnold",
    "postType": "page",
    "slug": "/postX",
    "status":"draft",
    "publishOn": "2022-09-27T18:00:00",
    "slug": "my-url",
    "schema": "{\r\n \"@context\": \"https:\/\/schema.org\", \r\n \"@type\": \"Person\"\r\n }",
    "tags":[3,1],
    "featureImageUrl": "http://locahlhost.com/image.img"
}