POST http://localhost:3300/posts/create
Content-Type: application/json


POST http://localhost:3300/posts/create
Content-Type: application/json
{
    "title": "Arnold",
    "postType": "page",
    "slug": "/postX",
    "status":"draft",
    "publishOn": "2022-09-27T18:00:00",
    "slug": "my-ur25",
    "schema": "{\r\n \"@context\": \"https:\/\/schema.org\", \r\n \"@type\": \"Person\"\r\n }",
    "featureImageUrl": "http://locahlhost.com/image.img",
    "metaOptions":{
            "metaValue":"{\"sidebarEnabled\":true, \"footerActive\":true }"
        },
    "authorId": 1,
    "tags": [7,8]
   
}