POST http://localhost:3300/users/
Content-Type: application/json
{
    "firstName": "Arnold",
    "lastName": "Bayema",
    "email": "abayema123@gmail.com",
    "password": "password@1234",
    "isTrue": true // will be ignore due to the whitelist in the main.TS
}

POST http://localhost:3300/users/createExpress
Content-Type: application/json
{
    "firstname": "Arnold",
    "lastname": "Bayema",
    "email": "abayema123@gmail.com",
    "password": "1234"
}