POST http://localhost:3300/users/
Content-Type: application/json
{
    "firstName": "John",
    "lastName": "BaDoeyema",
    "email": "abayema@gmail.com",
    "password": "password@1234"
}

POST http://localhost:3300/users/createExpress
Content-Type: application/json
{
    "firstname": "Arnold",
    "lastname": "Bayema",
    "email": "abayema123@gmail.com",
    "password": "1234"
}